defmodule CcxtOcx.Struct do
  @moduledoc """
  Declarative macro for CCXT-shaped typed structs (Task 8, v0.1 data plane).

  Usage:

      defmodule CcxtOcx.Ticker do
        use CcxtOcx.Struct

        field :symbol, :string, from: "symbol"
        field :last, :money_string, from: "last"
        field :timestamp, :timestamp_ms, from: "timestamp"
        field :info, :map, from: "info"
      end

  Each `field/3` is validated at compile time via NimbleOptions (unknown type tag
  produces a precise error). The macro emits:

  - `defstruct` with the declared keys (all optional)
  - `@type t()`
  - `from_ccxt(raw :: map() | list()) :: t() | nil` — the hydration function
    consumed by `defunified` (Task 7) and the `CcxtOcx.Structs` facade.

  Money fields are always emitted as strings (never floats). Timestamps are
  integers (ms since epoch) or nil. This is the canonical contract that both the
  JS adapter and future native adapters converge on.
  """

  @type tag :: :string | :integer | :timestamp_ms | :money_string | :list | :map | :bool

  @field_schema NimbleOptions.new!(
                  name: [
                    type: :atom,
                    doc: "Elixir field name (atom) in the generated struct."
                  ],
                  type: [
                    type: {:in, [:string, :integer, :timestamp_ms, :money_string, :list, :map, :bool]},
                    doc: "Semantic type tag. :money_string and :timestamp_ms trigger conversion."
                  ],
                  from: [
                    type: :string,
                    doc: "CCXT/JS key in the raw map returned by QuickBEAM (string key)."
                  ]
                )

  @doc """
  Declares one field of a CCXT-shaped struct inside a `use CcxtOcx.Struct` module.

  Each call is validated at compile time using a `NimbleOptions` schema.
  Unknown type tags will raise a clear error immediately.

  ## Examples

      field :last,      :money_string, from: "last"
      field :timestamp, :timestamp_ms, from: "timestamp"
      field :info,      :map,          from: "info"

  The `:from` key is the string key that will be looked up in the raw map
  returned by CCXT via QuickBEAM.
  """
  @spec field(atom(), tag(), keyword()) :: Macro.t()
  defmacro field(name, type, opts) when is_atom(name) do
    # Validate immediately so unknown tags fail at the declaration site with a
    # good Nimble error (not a cryptic macro expansion failure later).
    _ = NimbleOptions.validate!([name: name, type: type, from: opts[:from]], @field_schema)

    from = Keyword.get(opts, :from, Atom.to_string(name))

    quote do
      @ccxt_fields {unquote(name), unquote(type), unquote(from)}
    end
  end

  @doc """
  Two-argument convenience that defaults `from:` to `Atom.to_string(name)`.

  Equivalent to `field(name, type, [])`. Most call sites pass `from:` explicitly,
  but the two-arg form is useful when the Elixir field name already matches the
  CCXT key (e.g. `field :symbol, :string`).
  """
  @spec field(atom(), tag()) :: Macro.t()
  defmacro field(name, type) when is_atom(name) do
    quote do
      CcxtOcx.Struct.field(unquote(name), unquote(type), [])
    end
  end

  @doc """
  Sets up a module to use the `CcxtOcx.Struct` declarative field syntax.

  Injects `field/3`, registers the `@ccxt_fields` attribute, and schedules
  the code generation via `@before_compile`.
  """
  @spec __using__(keyword()) :: Macro.t()
  defmacro __using__(_opts) do
    quote do
      import CcxtOcx.Struct, only: [field: 3]

      Module.register_attribute(__MODULE__, :ccxt_fields, accumulate: true)
      @before_compile CcxtOcx.Struct
    end
  end

  @doc """
  Internal callback that runs at the end of the struct module definition
  to generate the actual `defstruct`, `@type`, and `from_ccxt/1` implementation
  based on the accumulated `field/3` declarations.
  """
  @spec __before_compile__(Macro.Env.t()) :: Macro.t()
  defmacro __before_compile__(env) do
    fields = env.module |> Module.get_attribute(:ccxt_fields) |> Enum.reverse()

    if fields == [] do
      raise CompileError,
        description: "CcxtOcx.Struct module must declare at least one `field/3`.",
        file: env.file,
        line: env.line
    end

    struct_fields = Enum.map(fields, fn {name, _type, _from} -> name end)

    # Generate the from_ccxt implementation body as a series of assignments
    # so the expanded code is readable in `mix docs` and stacktraces.
    from_ccxt_body =
      quote do
        @doc """
        Hydrates a raw CCXT value (typically a string-keyed map from QuickBEAM)
        into a `t()`.

        Accepts `nil`, a pre-hydrated `t()` (idempotent), a `map()` of the
        CCXT-shaped fields, or a `list()` (delegated to `from_list/1`).

        Generated by `use CcxtOcx.Struct`; see `CcxtOcx.Struct` for the macro
        contract and the supported semantic type tags.
        """
        @spec from_ccxt(map() | list() | t() | nil) :: t() | nil
        def from_ccxt(nil), do: nil

        # Already-hydrated values pass through unchanged (idempotent in
        # pipelines). MUST precede the is_map clause — structs are maps.
        def from_ccxt(%__MODULE__{} = s), do: s

        def from_ccxt(raw) when is_map(raw) do
          unquote(build_map_hydration(fields))
        end

        def from_ccxt(raw) when is_list(raw) do
          from_list(raw)
        end
      end

    quote do
      @enforce_keys []
      defstruct unquote(struct_fields)

      @type t :: %__MODULE__{unquote_splicing(build_type_spec(fields))}

      unquote(from_ccxt_body)

      @doc """
      Hydrates a positional list (CCXT's list-shaped return form, e.g. `OHLCV`).

      The default implementation raises — list-shaped CCXT returns live in
      bespoke modules (see `CcxtOcx.Candle`) that hand-roll their own
      `from_ccxt/1` and `from_list/1` instead of using the `field/3` DSL.
      """
      @spec from_list([term()]) :: t() | nil | no_return()
      def from_list(_), do: raise("from_list/1 not implemented for #{__MODULE__}")

      @doc "Returns the list of declared `{name, type, from}` tuples (introspection)."
      @spec __ccxt_fields__() :: [{atom(), CcxtOcx.Struct.tag(), String.t()}]
      def __ccxt_fields__, do: unquote(Macro.escape(fields))
    end
  end

  # --- Pure normalizers (unit-testable, no macro magic) ------------------------

  @doc """
  Normalizes a raw value coming from CCXT (via QuickBEAM) according to the
  semantic type tag declared in a struct field.

  This is the central conversion function used by all generated `from_ccxt/1`
  implementations.

  ## Supported tags

  - `:money_string`  — numbers or strings are turned into strings (never floats);
                       whole-number floats become integer strings to dodge
                       `Float.to_string/1`'s scientific notation
  - `:timestamp_ms`  — coerced to integer milliseconds since epoch
  - `:integer`       — truncated to integer
  - `:string`        — stringified
  - `:list`          — wrapped if necessary
  - `:map`           — passed through (or turned into empty map)
  - `:bool`          — `true`/`false` passed through, anything else `nil`

  Unknown tags fall back to identity.
  """
  @spec normalize(term(), tag() | atom()) :: term()
  def normalize(value, tag) do
    do_normalize(value, tag)
  end

  defp do_normalize(value, :money_string) do
    case value do
      nil ->
        nil

      v when is_integer(v) ->
        Integer.to_string(v)

      # Whole-number floats become integer strings — avoids Float.to_string's
      # scientific notation for round magnitudes (`70_000.0` → `"7.0e4"`).
      v when is_float(v) and v == trunc(v) ->
        v |> trunc() |> Integer.to_string()

      v when is_float(v) ->
        Float.to_string(v)

      v when is_binary(v) ->
        v

      _ ->
        nil
    end
  end

  defp do_normalize(value, :timestamp_ms) do
    case value do
      nil ->
        nil

      v when is_number(v) ->
        trunc(v)

      v when is_binary(v) ->
        case Integer.parse(v) do
          {i, _} -> i
          _ -> nil
        end

      _ ->
        nil
    end
  end

  defp do_normalize(value, :integer) do
    case value do
      nil ->
        nil

      v when is_number(v) ->
        trunc(v)

      v when is_binary(v) ->
        case Integer.parse(v) do
          {i, _} -> i
          _ -> nil
        end

      _ ->
        nil
    end
  end

  defp do_normalize(value, :string) do
    case value do
      nil -> nil
      v when is_binary(v) -> v
      v -> to_string(v)
    end
  end

  defp do_normalize(value, :list) when is_list(value), do: value
  defp do_normalize(nil, :list), do: []
  defp do_normalize(value, :list), do: List.wrap(value)

  defp do_normalize(value, :map) when is_map(value), do: value
  defp do_normalize(nil, :map), do: %{}
  defp do_normalize(_value, :map), do: %{}

  defp do_normalize(true, :bool), do: true
  defp do_normalize(false, :bool), do: false
  defp do_normalize(_value, :bool), do: nil

  defp do_normalize(value, _other), do: value

  # --- Internal builders (kept out of the public macro surface) ----------------

  defp build_type_spec(fields) do
    Enum.map(fields, fn {name, type, _from} ->
      {name, type_for_spec(type)}
    end)
  end

  defp type_for_spec(:money_string), do: quote(do: String.t() | nil)
  defp type_for_spec(:timestamp_ms), do: quote(do: integer() | nil)
  defp type_for_spec(:integer), do: quote(do: integer() | nil)
  defp type_for_spec(:string), do: quote(do: String.t() | nil)
  defp type_for_spec(:list), do: quote(do: list())
  defp type_for_spec(:map), do: quote(do: map())
  defp type_for_spec(:bool), do: quote(do: boolean() | nil)
  defp type_for_spec(_), do: quote(do: term())

  defp build_map_hydration(fields) do
    pairs =
      Enum.map(fields, fn {name, type, from} ->
        {name, quote(do: CcxtOcx.Struct.normalize(Map.get(raw, unquote(from)), unquote(type)))}
      end)

    quote do
      %__MODULE__{unquote_splicing(pairs)}
    end
  end
end
