defmodule CcxtOcx do
  @moduledoc """
  ccxt_ocx — macro-first Elixir wrapper around CCXT running inside QuickBEAM.

  The **only** public entrypoint is the `use` macro:

      use CcxtOcx, exchanges: [:binance, :deribit, :okx]
      use CcxtOcx, tier: :tier1
      use CcxtOcx, exchanges: :all     # heavy — you almost certainly do not want this

  Everything else (per-exchange modules, unified methods, typed structs) is
  generated at compile time from CCXT's own TypeScript declarations.

  ## Why explicit scope?

  The CCXT surface is ~150 unified methods × 100+ exchanges. Generating wrappers
  for all of them by default would add 30–60 s of compile time and several MB of
  BEAM to every consumer. Requiring an explicit declaration (Option A) makes the
  cost visible on day one — the same philosophy as `Phoenix.Router`.

  ## Telemetry

  All instrumentation is under the `[:ccxt_ocx]` prefix.

  - `[:ccxt_ocx, :runtime, :memory]` — emitted by `CcxtOcx.Runtime.memory/1`,
    `CcxtOcx.RuntimePool.memory/1`, and at worker init/terminate.
  - `[:ccxt_ocx, :rest, :start|stop|exception]` and `[:ccxt_ocx, :ws, :tick]`
    are reserved for the Phase 2/3 macro layers.

  See `CcxtOcx.Telemetry` for the full contract, shapes, and examples.
  """

  alias CcxtOcx.Macros.Use

  defmacro __using__(opts) do
    caller = %{file: __CALLER__.file, line: __CALLER__.line}

    scope = Use.validate_and_normalize(opts, caller)

    # Emit one real Elixir module per declared exchange. The `unless
    # Code.ensure_loaded?` guard makes the first `use CcxtOcx, exchanges: [:id]`
    # in a compile unit "win" so two consumer modules can both declare overlapping
    # scopes without triggering Elixir's module-redefinition warning (which fails
    # under --warnings-as-errors). All emitted modules for the same exchange id
    # are byte-identical in v0.1; Task 9 will revisit ownership when per-exchange
    # capability tables ship.
    per_exchange_modules =
      for id <- scope.exchanges do
        module_name = Module.concat(__MODULE__, Macro.camelize(to_string(id)))
        mod_doc = moduledoc_for(scope, id)

        quote do
          if !Code.ensure_loaded?(unquote(module_name)) do
            defmodule unquote(module_name) do
              @moduledoc unquote(mod_doc)

              @doc "The canonical CCXT exchange id (atom) for this generated module."
              def __exchange_id__, do: unquote(id)

              # TODO(Task 9): replace `__generated_by_task_6b__/0` with real
              # `defexchange`-emitted capability surface (has?/1, urls/0, etc.).
              # Tests and the Task 7 `defunified` integration use this marker
              # to detect 6b-stub modules vs Task 9-enriched ones.
              def __generated_by_task_6b__, do: true
            end
          end
        end
      end

    per_exchange_modules
  end

  defp moduledoc_for(%{mode: :all}, _id) do
    """
    Generated by `use CcxtOcx, exchanges: :all`.

    **Warning**: this brings in the entire CCXT surface (~150 methods × 100+
    venues). Compile time and BEAM size will be large. Prefer an explicit
    list or `tier: :tier1` unless you truly need everything.
    """
  end

  defp moduledoc_for(scope, id) do
    """
    Generated by `use CcxtOcx, #{inspect(scope.source)}`.

    Source of truth for this exchange's surface lives in
    `CcxtOcx.Declarations` + the committed `priv/ccxt_surface.exs`.

    Per-exchange capability data (`has`, `urls`, `timeframes`, ...) will be
    populated by Task 9 (`defexchange`) via `CcxtOcx.Macros.ExchangeCaps`
    and cached at `priv/exchange_caps/#{id}.exs`.
    For now only `__exchange_id__/0` and a generation marker are present.
    """
  end
end
