defmodule CcxtOcx do
  @moduledoc """
  ccxt_ocx — macro-first Elixir wrapper around CCXT running inside QuickBEAM.

  The **only** public entrypoint is the `use` macro:

      use CcxtOcx, exchanges: [:binance, :deribit, :okx]
      use CcxtOcx, tier: :tier1
      use CcxtOcx, exchanges: :all     # heavy — you almost certainly do not want this

  Everything else (per-exchange modules, unified methods, typed structs) is
  generated at compile time from CCXT's own TypeScript declarations.

  The six core data-plane structs (`CcxtOcx.Ticker`, `OrderBook`, `Candle`,
  `Trade`, `Market`, `Currency`) are always available (no `use` required) and
  are the return shapes for the macro-generated fetch/watch wrappers.

  ## Why explicit scope?

  The CCXT surface is ~150 unified methods × 100+ exchanges. Generating wrappers
  for all of them by default would add 30–60 s of compile time and several MB of
  BEAM to every consumer. Requiring an explicit declaration (Option A) makes the
  cost visible on day one — the same philosophy as `Phoenix.Router`.

  ## Telemetry

  All instrumentation is under the `[:ccxt_ocx]` prefix.

  - `[:ccxt_ocx, :runtime, :memory]` — emitted by `CcxtOcx.Runtime.memory/1`,
    `CcxtOcx.RuntimePool.memory/1`, and at worker init/terminate.
  - `[:ccxt_ocx, :rest, :start|stop|exception]` and `[:ccxt_ocx, :ws, :tick]`
    are reserved for the Phase 2/3 macro layers.

  See `CcxtOcx.Telemetry` for the full contract, shapes, and examples.
  """

  alias CcxtOcx.Macros.Use

  defmacro __using__(opts) do
    caller = %{file: __CALLER__.file, line: __CALLER__.line}

    scope = Use.validate_and_normalize(opts, caller)

    # Emit one real Elixir module per declared exchange. The `unless
    # Code.ensure_loaded?` guard makes the first `use CcxtOcx, exchanges: [:id]`
    # in a compile unit "win" so two consumer modules can both declare overlapping
    # scopes without triggering Elixir's module-redefinition warning (which fails
    # under --warnings-as-errors). All emitted modules for the same exchange id
    # are byte-identical; the first declaration owns the (identical) capability
    # snapshot produced by `defexchange`.
    per_exchange_modules =
      for id <- scope.exchanges do
        module_name = Module.concat(__MODULE__, Macro.camelize(to_string(id)))
        mod_doc = moduledoc_for(scope, id)

        quote do
          if !Code.ensure_loaded?(unquote(module_name)) do
            defmodule unquote(module_name) do
              @moduledoc unquote(mod_doc)

              alias CcxtOcx.Macros.Exchange

              require Exchange

              @doc "The canonical CCXT exchange id (atom) for this generated module."
              def __exchange_id__, do: unquote(id)

              # Task 9 (`defexchange`) — emits has?/1, urls/0, timeframes/0, the
              # Exchange struct, @has_table (for Task 7 gating), and @external_resource
              # wiring back to the caps cache. Runs at compile time of the consumer.
              Exchange.defexchange(unquote(id))
            end
          end
        end
      end

    per_exchange_modules
  end

  defp moduledoc_for(%{mode: :all}, _id) do
    """
    Generated by `use CcxtOcx, exchanges: :all`.

    **Warning**: this brings in the entire CCXT surface (~150 methods × 100+
    venues). Compile time and BEAM size will be large. Prefer an explicit
    list or `tier: :tier1` unless you truly need everything.
    """
  end

  defp moduledoc_for(scope, id) do
    """
    Generated by `use CcxtOcx, #{inspect(scope.source)}`.

    Source of truth for this exchange's surface lives in
    `CcxtOcx.Declarations` + the committed `priv/ccxt_surface.exs`.

    Per-exchange capability data (`has`, `urls`, `timeframes`, ...) is
    populated by Task 9 (`defexchange`) via `CcxtOcx.Macros.ExchangeCaps`
    and cached at `priv/exchange_caps/#{id}.exs`.
    The generated module now exposes `has?/1`, `urls/0`, `timeframes/0`,
    the `Exchange` struct, and a compile-time `@has_table` for Task 7.
    """
  end
end
